name: Self-hosted runners test

on: [push]

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      env:
        PIPENV_NOSPIN: 1
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Test with pytest
      run: pipenv run pytest
